import { BaseQueueProvider } from '../core/base-provider.js';
import { asText, jsonCodec } from '../core/codec.js';
import { createConsumer } from '../core/lifecycle.js';
import { loadOptional } from '../core/load-optional.js';
import type { RedisConfig } from '../config.js';
import type { ConsumerOptions, PublishOptions, PublishResult, QueueAcknowledgement, QueueCapabilities, QueueConsumer, QueueHandler, QueueMessage } from '../core/types.js';

export interface RedisPublishOptions { readonly maxLength?: number; readonly approximate?: boolean; }
export interface RedisConsumerOptions { readonly blockMs?: number; readonly count?: number; }
export type RedisAcknowledgement = QueueAcknowledgement<unknown>;
type RedisClient = Awaited<ReturnType<typeof import('redis')['createClient']>>;
export class RedisProvider extends BaseQueueProvider<'redis'> {
  readonly name = 'redis' as const;
  readonly capabilities: QueueCapabilities;
  #sdk: typeof import('redis') | undefined; #client: RedisClient | undefined; readonly #subscribers = new Set<RedisClient>();
  constructor(readonly config: RedisConfig) { super(); this.capabilities = config.mode === 'streams' ? { kind: 'stream', publish: true, consume: true, ack: true, replay: true, consumerGroups: true, ordering: true } : { kind: 'pubsub', publish: true, consume: true }; }
  async #module(): Promise<typeof import('redis')> { return this.#sdk ??= await loadOptional<typeof import('redis')>('redis', this.name); }
  async #getClient(): Promise<RedisClient> { if (this.#client) return this.#client; this.#client = (await this.#module()).createClient({ url: this.config.url }); this.#client.on('error', () => undefined); await this.#client.connect(); return this.#client; }
  async publish<TPayload>(destination: string, message: QueueMessage<TPayload>, options?: PublishOptions<RedisPublishOptions>): Promise<PublishResult<'redis', number | string>> {
    let result: PublishResult<'redis', number | string> | undefined; await this.operation({ provider: this.name, operation: 'publish', destination, traceId: message.traceId, correlationId: message.correlationId, metadata: message.metadata }, async () => { const client = await this.#getClient(); const encoded = asText(jsonCodec.encode(message)); const native = this.config.mode === 'pubsub' ? await client.publish(destination, encoded) : await client.sendCommand<string>(['XADD', destination, ...(options?.native?.maxLength ? ['MAXLEN', options.native.approximate === false ? '=' : '~', String(options.native.maxLength)] : []), '*', 'data', encoded]); result = { ok: true, provider: this.name, messageId: typeof native === 'string' ? native : message.id, native }; }); return result!;
  }
  async consume<TPayload>(destination: string, handler: QueueHandler<TPayload, unknown, RedisAcknowledgement>, options?: ConsumerOptions<RedisConsumerOptions>): Promise<QueueConsumer> { return this.config.mode === 'pubsub' ? this.#consumePubsub(destination, handler, options) : this.#consumeStream(destination, handler, options); }
  async #consumePubsub<TPayload>(destination: string, handler: QueueHandler<TPayload, unknown, RedisAcknowledgement>, _options?: ConsumerOptions<RedisConsumerOptions>): Promise<QueueConsumer> { const subscriber = (await this.#getClient()).duplicate(); subscriber.on('error', () => undefined); await subscriber.connect(); this.#subscribers.add(subscriber); const controller = new AbortController(); await subscriber.subscribe(destination, async (raw) => { const envelope = jsonCodec.decode(raw) as QueueMessage<TPayload>; const ack: RedisAcknowledgement = { native: undefined, complete: async () => undefined }; await handler({ message: { ...envelope, headers: envelope.headers ?? {}, native: raw }, ack, signal: controller.signal }); }); return createConsumer({ close: async () => { controller.abort(); this.#subscribers.delete(subscriber); await subscriber.unsubscribe(destination); await subscriber.quit(); } }); }
  async #consumeStream<TPayload>(destination: string, handler: QueueHandler<TPayload, unknown, RedisAcknowledgement>, options?: ConsumerOptions<RedisConsumerOptions>): Promise<QueueConsumer> { const client = await this.#getClient(); const group = this.config.group ?? 'queuekit'; const consumerName = this.config.consumer ?? `queuekit-${Math.random().toString(36).slice(2)}`; try { await client.sendCommand(['XGROUP', 'CREATE', destination, group, '0', 'MKSTREAM']); } catch { /* group can already exist */ }
    const controller = new AbortController(); let paused = false; const loop = async () => { while (!controller.signal.aborted) { if (paused) { await new Promise((resolve) => setTimeout(resolve, 20)); continue; } const response = await client.sendCommand<unknown>(['XREADGROUP', 'GROUP', group, consumerName, 'COUNT', String(options?.native?.count ?? 1), 'BLOCK', String(options?.native?.blockMs ?? 1000), 'STREAMS', destination, '>']); for (const item of streamEntries(response)) { const envelope = jsonCodec.decode(item.data) as QueueMessage<TPayload>; let settled = false; const ack: RedisAcknowledgement = { native: item.raw, complete: async () => { if (!settled) { await client.sendCommand(['XACK', destination, group, item.id]); settled = true; } } }; await handler({ message: { ...envelope, id: envelope.id ?? item.id, headers: envelope.headers ?? {}, native: item.raw }, ack, signal: controller.signal }); if (options?.autoAck) await ack.complete(); } } }; void loop(); return createConsumer({ pause: async () => { paused = true; }, resume: async () => { paused = false; }, close: async () => { controller.abort(); } }); }
  native(): RedisClient | undefined { return this.#client; }
  async close(): Promise<void> { this.markClosed(); await Promise.all([...this.#subscribers].map((client) => client.quit())); await this.#client?.quit(); this.#subscribers.clear(); this.#client = undefined; }
}
function streamEntries(value: unknown): readonly { readonly id: string; readonly data: string; readonly raw: unknown }[] { if (!Array.isArray(value)) return []; const entries: { id: string; data: string; raw: unknown }[] = []; for (const stream of value) { if (!Array.isArray(stream) || !Array.isArray(stream[1])) continue; for (const entry of stream[1]) { if (!Array.isArray(entry) || typeof entry[0] !== 'string' || !Array.isArray(entry[1])) continue; const index = entry[1].indexOf('data'); if (index >= 0 && typeof entry[1][index + 1] === 'string') entries.push({ id: entry[0], data: entry[1][index + 1], raw: entry }); } } return entries; }
export async function createRedisQueue(config: RedisConfig): Promise<RedisProvider> { return new RedisProvider(config); }
