import type { DeleteMessageCommandOutput, Message, ReceiveMessageCommandInput, SendMessageCommandInput, SendMessageCommandOutput } from '@aws-sdk/client-sqs';
import { BaseQueueProvider } from '../core/base-provider.js';
import { asText, jsonCodec } from '../core/codec.js';
import { createConsumer } from '../core/lifecycle.js';
import { loadOptional } from '../core/load-optional.js';
import type { SqsConfig } from '../config.js';
import type { ConsumerOptions, PublishOptions, PublishResult, QueueAcknowledgement, QueueCapabilities, QueueConsumer, QueueHandler, QueueMessage } from '../core/types.js';

export type SqsPublishOptions = Omit<SendMessageCommandInput, 'QueueUrl' | 'MessageBody'>;
export type SqsConsumerOptions = Omit<ReceiveMessageCommandInput, 'QueueUrl'>;
export type SqsAcknowledgement = QueueAcknowledgement<Message>;
export class SqsProvider extends BaseQueueProvider<'sqs'> {
  readonly name = 'sqs' as const;
  readonly capabilities: QueueCapabilities = { kind: 'queue', publish: true, consume: true, batchPublish: true, delayed: true, retries: true, ttl: false, deadLetter: true, ack: true, nack: true, consumerGroups: true, ordering: true };
  #sdk: typeof import('@aws-sdk/client-sqs') | undefined; #client: import('@aws-sdk/client-sqs').SQSClient | undefined;
  constructor(readonly config: SqsConfig) { super(); }
  async #module(): Promise<typeof import('@aws-sdk/client-sqs')> { return this.#sdk ??= await loadOptional<typeof import('@aws-sdk/client-sqs')>('@aws-sdk/client-sqs', this.name); }
  async #getClient(): Promise<import('@aws-sdk/client-sqs').SQSClient> { if (this.#client) return this.#client; const { SQSClient } = await this.#module(); this.#client = new SQSClient({ region: this.config.region, endpoint: this.config.endpoint, credentials: this.config.credentials as never }); return this.#client; }
  #url(destination: string): string { return destination || this.config.queueUrl || ''; }
  async publish<TPayload>(destination: string, message: QueueMessage<TPayload>, options?: PublishOptions<SqsPublishOptions>): Promise<PublishResult<'sqs', SendMessageCommandOutput>> { const queueUrl = this.#url(destination); if (!queueUrl) throw new Error('SQS publish requires a destination or config.queueUrl.'); let result: PublishResult<'sqs', SendMessageCommandOutput> | undefined; await this.operation({ provider: this.name, operation: 'publish', destination: queueUrl, traceId: message.traceId, correlationId: message.correlationId, metadata: message.metadata }, async () => { const { SendMessageCommand } = await this.#module(); const native = await (await this.#getClient()).send(new SendMessageCommand({ ...options?.native, QueueUrl: queueUrl, MessageBody: asText(jsonCodec.encode(message)), DelaySeconds: options?.delay ? Math.floor(options.delay / 1000) : options?.native?.DelaySeconds, MessageDeduplicationId: options?.idempotencyKey ?? options?.native?.MessageDeduplicationId })); result = { ok: true, provider: this.name, messageId: native.MessageId, sequenceNumber: native.SequenceNumber, native }; }); return result!; }
  async consume<TPayload>(destination: string, handler: QueueHandler<TPayload, Message, SqsAcknowledgement>, options?: ConsumerOptions<SqsConsumerOptions>): Promise<QueueConsumer> { const queueUrl = this.#url(destination); if (!queueUrl) throw new Error('SQS consume requires a destination or config.queueUrl.'); const client = await this.#getClient(); const { ReceiveMessageCommand, DeleteMessageCommand, ChangeMessageVisibilityCommand } = await this.#module(); const controller = new AbortController(); let paused = false; const run = async () => { while (!controller.signal.aborted) { if (paused) { await new Promise((resolve) => setTimeout(resolve, 20)); continue; } const response = await client.send(new ReceiveMessageCommand({ QueueUrl: queueUrl, MaxNumberOfMessages: options?.native?.MaxNumberOfMessages ?? 1, WaitTimeSeconds: options?.native?.WaitTimeSeconds ?? 1, ...options?.native })); await Promise.all((response.Messages ?? []).map(async (raw) => { if (!raw.Body || !raw.ReceiptHandle) return; const envelope = jsonCodec.decode(raw.Body) as QueueMessage<TPayload>; let settled = false; const ack: SqsAcknowledgement = { native: raw, complete: async () => { if (!settled) { await client.send(new DeleteMessageCommand({ QueueUrl: queueUrl, ReceiptHandle: raw.ReceiptHandle! })); settled = true; } }, retry: async (retry) => { if (!settled) { await client.send(new ChangeMessageVisibilityCommand({ QueueUrl: queueUrl, ReceiptHandle: raw.ReceiptHandle!, VisibilityTimeout: Math.floor((retry?.delay ?? 0) / 1000) })); settled = true; } } }; await handler({ message: { id: raw.MessageId, type: envelope.type, payload: envelope.payload, headers: envelope.headers ?? {}, timestamp: envelope.timestamp, correlationId: envelope.correlationId, causationId: envelope.causationId, traceId: envelope.traceId, native: raw }, ack, signal: controller.signal }); if (options?.autoAck) await ack.complete(); })); } }; void run(); return createConsumer({ pause: async () => { paused = true; }, resume: async () => { paused = false; }, close: async () => { controller.abort(); } }); }
  native(): import('@aws-sdk/client-sqs').SQSClient | undefined { return this.#client; }
  async close(): Promise<void> { this.markClosed(); this.#client?.destroy(); this.#client = undefined; }
}
export async function createSqs(config: SqsConfig): Promise<SqsProvider> { return new SqsProvider(config); }
